import { cookies } from "next/headers";
import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const inter = Roboto({ subsets: ["latin"], weight: ["100", "300", "400","500","700","900"] });

export const metadata: Metadata = {
  title: "Instagram clone with socket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth?: React.ReactNode;
}) {
  const cookieStore = cookies();
  const auth_token = cookieStore.get("auth_token");

  if (auth_token == undefined) {
    return (
      <html lang="en">
        <body className={inter.className}>{auth}</body>
      </html>
    );
  } else {
    return (
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    );
  }
}
